public enum TokenType {
    LEFT_PAREN, RIGHT_PAREN, LEFT_BRACE, RIGHT_BRACE,
    COMMA, DOT, MINUS, PLUS, SEMICOLON, SLASH, STAR,
    LEFT_BRACKET, RIGHT_BRACKET,
    AMPERSAND,
    PERCENT,

    // One or two character tokens.
    BANG, BANG_EQUAL,
    EQUAL, EQUAL_EQUAL,
    GREATER, GREATER_EQUAL,
    LESS, LESS_EQUAL,

    // Literals.
    IDENTIFIER, STRING, NUMBER,

    // Keywords.
    DOUBLE_AMPERSAND, DOUBLE_PIPE, ELSE, FOR, IF,
    PRINT, RETURN, WHILE,
    INT,

    EOF
}
